# Compiles the overlay renderer's HLSL shaders to bytecode and embeds them
# as C arrays in headers, so the mod DLL doesn't need D3DCompiler at runtime
# (avoids a runtime dependency on d3dcompiler_47.dll being present/loadable).
#
# Usage: powershell -File compile_shaders.ps1

$ErrorActionPreference = "Stop"
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path

$fxcCandidates = @(
    "C:\Program Files (x86)\Windows Kits\10\bin\10.0.26100.0\x64\fxc.exe",
    "C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\x64\fxc.exe"
)
$fxc = $fxcCandidates | Where-Object { Test-Path $_ } | Select-Object -First 1
if (-not $fxc) {
    throw "fxc.exe not found -- checked: $($fxcCandidates -join ', ')"
}

function Compile-Shader($hlslFile, $profile, $varName, $outHeader) {
    $csoFile = [System.IO.Path]::ChangeExtension($hlslFile, ".cso")
    & $fxc /nologo /T $profile /E main /Fo $csoFile $hlslFile
    if ($LASTEXITCODE -ne 0) { throw "fxc failed for $hlslFile" }

    $bytes = [System.IO.File]::ReadAllBytes($csoFile)
    $sb = New-Object System.Text.StringBuilder
    [void]$sb.AppendLine("// Generated by compile_shaders.ps1 from $(Split-Path -Leaf $hlslFile) -- do not edit by hand.")
    [void]$sb.AppendLine("#pragma once")
    [void]$sb.AppendLine("static const unsigned char $varName[] = {")
    for ($i = 0; $i -lt $bytes.Length; $i += 16) {
        $chunk = $bytes[$i..[Math]::Min($i + 15, $bytes.Length - 1)]
        [void]$sb.AppendLine("    " + (($chunk | ForEach-Object { "0x{0:x2}" -f $_ }) -join ", ") + ",")
    }
    [void]$sb.AppendLine("};")
    [void]$sb.AppendLine("static const unsigned int ${varName}_size = $($bytes.Length);")
    [System.IO.File]::WriteAllText($outHeader, $sb.ToString())
    Remove-Item $csoFile
    Write-Host "Wrote $outHeader ($($bytes.Length) bytes)"
}

Compile-Shader "$scriptDir\quad_vs.hlsl" "vs_4_0" "g_quad_vs" "$scriptDir\quad_vs.h"
Compile-Shader "$scriptDir\quad_ps.hlsl" "ps_4_0" "g_quad_ps" "$scriptDir\quad_ps.h"
Compile-Shader "$scriptDir\sprite_vs.hlsl" "vs_4_0" "g_sprite_vs" "$scriptDir\sprite_vs.h"
Compile-Shader "$scriptDir\sprite_ps.hlsl" "ps_4_0" "g_sprite_ps" "$scriptDir\sprite_ps.h"
